"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";

// const export metadata: Metadata = {
//     title: "Next.js",
//     description: "Generated by Next.js",
// };

const navLinks = [
    { name: "Login", href: "/login" },
    { name: "Register", href: "/register" },
];

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const pathname = usePathname();
    const [state, setState] = useState("");

    return (
        <div>
            <div className="p-4">
                {/* Since this is a layout.tsx file, state will not chnage when navigating to child pages */}
                {/* If using a template.tsx file, state will revert to it's initial state when giong to child pages */}
                <input
                    value={state}
                    type="text"
                    onChange={(e) => setState(e.target.value)}
                    className="outline rounded-sm"
                />
            </div>
            {navLinks.map((link) => {
                const isActive = pathname.startsWith(link.href);

                return (
                    <Link
                        href={link.href}
                        key={link.name}
                        className={
                            isActive
                                ? "text-yellow-400 font-serif font-bold"
                                : "text-blue-400"
                        }
                    >
                        {link.name} |{" "}
                    </Link>
                );
            })}
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Doloremque, voluptatibus?
            </p>
            {children}
        </div>
    );
}
