// Main layout page

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    // title: "Create Next App",            // string type
    title: {
        // object type
        absolute: "This overwrites everything when used on a page",
        default: "Default titles for pages w/o metadata",
        template: "%s | Post-TitleText", // %s = page specific title
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
